type ImageSource = number;

export const signImages: Record<string, ImageSource> = {
  "bike-lane.png": require("../../assets/signs/bike-lane.png"),
  "blind-spots.png": require("../../assets/signs/blind-spots.png"),
  "blue-curb.png": require("../../assets/signs/blue-curb.png"),
  "broken-white-lines.png": require("../../assets/signs/broken-white-lines.png"),
  "broken-yellow-line.png": require("../../assets/signs/broken-yellow-line.png"),
  "center-left-turn-lane.png": require("../../assets/signs/center-left-turn-lane.png"),
  "do-not-block-intersection.png": require("../../assets/signs/do-not-block-intersection.png"),
  "do-not-enter.png": require("../../assets/signs/do-not-enter.png"),
  "double-solid-white-lines.png": require("../../assets/signs/double-solid-white-lines.png"),
  "double-solid-yellow-lines.png": require("../../assets/signs/double-solid-yellow-lines.png"),
  "flashing-dont-walk.png": require("../../assets/signs/flashing-dont-walk.png"),
  "flashing-red-light.png": require("../../assets/signs/flashing-red-light.png"),
  "flashing-yellow-light.png": require("../../assets/signs/flashing-yellow-light.png"),
  "green-arrow.png": require("../../assets/signs/green-arrow.png"),
  "green-curb.png": require("../../assets/signs/green-curb.png"),
  "hov-diamond.png": require("../../assets/signs/hov-diamond.png"),
  "parallel-parking.png": require("../../assets/signs/parallel-parking.png"),
  "prohibition-sign.png": require("../../assets/signs/prohibition-sign.png"),
  "railroad-crossing.png": require("../../assets/signs/railroad-crossing.png"),
  "railroad-flashing-red.png": require("../../assets/signs/railroad-flashing-red.png"),
  "red-arrow.png": require("../../assets/signs/red-arrow.png"),
  "red-curb.png": require("../../assets/signs/red-curb.png"),
  "school-bus-red-lights.png": require("../../assets/signs/school-bus-red-lights.png"),
  "school-bus-yellow-lights.png": require("../../assets/signs/school-bus-yellow-lights.png"),
  "school-speed-limit.png": require("../../assets/signs/school-speed-limit.png"),
  "school-zone.png": require("../../assets/signs/school-zone.png"),
  "single-solid-white-line.png": require("../../assets/signs/single-solid-white-line.png"),
  "single-solid-yellow-line.png": require("../../assets/signs/single-solid-yellow-line.png"),
  "slow-moving-vehicle.png": require("../../assets/signs/slow-moving-vehicle.png"),
  "solid-green-light.png": require("../../assets/signs/solid-green-light.png"),
  "solid-red-light.png": require("../../assets/signs/solid-red-light.png"),
  "solid-yellow-light.png": require("../../assets/signs/solid-yellow-light.png"),
  "stop-sign.png": require("../../assets/signs/stop-sign.png"),
  "walk-signal.png": require("../../assets/signs/walk-signal.png"),
  "warning-diamond.png": require("../../assets/signs/warning-diamond.png"),
  "white-curb.png": require("../../assets/signs/white-curb.png"),
  "wrong-way.png": require("../../assets/signs/wrong-way.png"),
  "yellow-curb.png": require("../../assets/signs/yellow-curb.png"),
  "yield-line.png": require("../../assets/signs/yield-line.png"),
  "yield-sign.png": require("../../assets/signs/yield-sign.png"),
};
